mtianyan_mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_DATABASE=mxonline3 # name you want for the database
      - MYSQL_USER=root # change to whatever username you wantr
      - MYSQL_ROOT_PASSWORD=mtianyanroot #change to good root password
    ports:
      - "3311:3306"
    volumes:
      - "./db:/var/lib/mysql"

mtianyan_imooc:
  restart: always
  build: .
  ports:
    - "89:80"
  volumes:
    - .:/Mxonline3
  links:
    - mtianyan_mysql:mysql
  command: /usr/sbin/apachectl -DFOREGROUND



